version: "3.8"
services:
  postgres-diesel:
    image: postgres
    volumes:
      - postgres-diesel-vol:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: diesel_database
      POSTGRES_USER: diesel_username
      POSTGRES_PASSWORD: diesel_password
volumes:
  postgres-diesel-vol: